### ISSUE TITLE
The .exe file is malicious (Malware)

### ISSUE THREAD

**Issue by davidcforbes** [jtg-github/ConvertToOFX#7]
The ConvertToOFX.exe file is flagged as malicious malware by CrowdStrike's Hybrid-Analysis scanner:
http://www.hybrid-analysis.com/sample/c56731b2d7e6c97365229a7ac9af11aab93036114ba51e2c68cf65c7fe8ae9b6

**Comment by jtg-github** [comment]
I am fairly sure that it is inaccurate and a false positive. When I run it through Virus Total, it reports a clean binary: https://www.virustotal.com/gui/url/55e1c95c7aa064d8c9b45ab1b7c1a559f44e7e277868d2b9d525d6403927714a?nocache=1

It also seems that other small utilities are often on the receiving end of false positives. This is a blog post from 15 years ago describing the problem of false positives: https://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/
